import Script from "next/script";
import "./globals.css";
import { ViewportProvider } from "@/hooks/useViewPort";
import { ContextProvider } from "./contexts/ContextProvider";

export const metadata = {
  title: "Future",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ViewportProvider>
          <ContextProvider>{children}</ContextProvider>
        </ViewportProvider>
      </body>
    </html>
  );
}
